# Generated by Django 4.2.27 on 2026-03-01 13:47

from django.db import migrations


def seed_categories(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    categories_to_add = [
        "Fashion",
        "Food & Grocery",
        "Crafts & Art",
        "Beauty & Health",
        "Home & Living"
    ]
    for cat_name in categories_to_add:
        # Avoid creating duplicates if the migration is run on an environment that already has them
        Category.objects.get_or_create(name=cat_name)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_productimage_image'),
    ]

    operations = [
        migrations.RunPython(seed_categories, migrations.RunPython.noop),
    ]
