# Generated by Django 4.2.27 on 2026-03-01 10:40

from django.db import migrations
from django.utils.text import slugify

def populate_store_slugs(apps, schema_editor):
    Store = apps.get_model('users', 'Store')
    for store in Store.objects.all():
        if not store.slug:
            original_slug = slugify(store.store_name)
            new_slug = original_slug
            counter = 1
            while Store.objects.filter(slug=new_slug).exclude(pk=store.pk).exists():
                new_slug = f"{original_slug}-{counter}"
                counter += 1
            store.slug = new_slug
            store.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_store_slug'),
    ]

    operations = [
        migrations.RunPython(populate_store_slugs, migrations.RunPython.noop),
    ]
