# Generated by Django 4.2.23 on 2026-01-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('evidence_text', models.TextField(blank=True, help_text='Description of the issue')),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='disputes/')),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved_refund', 'Resolved (Refund)'), ('resolved_release', 'Resolved (Release Funds)'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
