# Generated by Django 4.2.27 on 2026-01-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code_hash', models.CharField(max_length=64)),
                ('purpose', models.CharField(choices=[('register', 'Register'), ('login', 'Login'), ('reset_password', 'Reset Password')], max_length=30)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('resend_count', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'purpose'], name='authenticat_email_eddb62_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='emailotp',
            constraint=models.UniqueConstraint(condition=models.Q(('is_verified', False)), fields=('email', 'purpose'), name='unique_active_otp_per_email_purpose'),
        ),
    ]
